version: 2
sources:
  - name: datafeed_shared_schema
    database: dbt_db
    schema: confirmed_layer
    
    tables:
      - name: stg_customers 
      - name: stg_payments
      - name: stg_orders
      - name: products
